### ISSUE TITLE
thoughts on things that are important

### ISSUE THREAD

**Issue by haileypate** [cityofaustin/open-data-suggestions#11]
- what sort of SLA do we want to have with the public?
- this could really help departments understand what their customers want... because some of us don't know! 
- how can we give the requestor feedback about what happens to their request after it's received by the city

**Comment by CodeMcConnell** [comment]
The SLA item was one that I suggested at the meetup. It was motivated by my experience as a member of the general public requesting data. It often seemed as if posts would go onto Socrata and receive no follow-up whatsoever. 

I don't know if SLA is the right term; I used it as a metaphor, On the website, I would probably label it as "What to Expect." Ideally, a requestor would get some kind of feedback within 10-15 business days, particularly if it's the sort of "that is not a city dataset" or "we cannot provide that data because it is sensitive." It would also be good to receive notice of technical challenges or time needed to publish data. 

It's probably a good idea to publish some kind of flowchart or process diagram to explain the process to the public.

**Comment by cronins** [comment]
Would the flow for a request be different for each department? I could see where it might take longer if data has to be scrubbed, or go through an approval chain. It's in the diagram, but the amount of time could be different for the department.

**Comment by haileypate** [comment]
@cronins I agree, the workflow is likely to be different for each department. I do like the idea of developing some language about "What to Expect" for suggestors, as mentioned by @CodeMcConnell. One question for us all to kick around: 
- [ ] For which parts of the workflow would we want to suggest standards?

**Comment by haileypate** [comment]
closing out, will still be avilable for review in archive as needed
